{
 "title": "Sailine Dashbaord",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"font-size: 130px; color: #e6ffcc\">Overview</p>"
   }
  },
  {
   "type": "gauge",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"OEE\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 15, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"OEE\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 15, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"OEE\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 15, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"OEE\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Data Table",
   "type": "table",
   "gridPos": { "h": 38, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"Avaliability\", \"Performance\", \"Quality\", \"OEE\", \"Total_Quality_Items\", \"time\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo ORDER BY \"time\" DESC "
    }
   ]
  },
  {
   "title": "Overview of OEE",
   "type": "barchart",
   "gridPos": { "h": 23, "w": 16, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"Avaliability\", \"Performance\", \"Quality\", \"OEE\", \"time\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"Flowmeter\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 28, "w": 9, "x": 4, "y": 43 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"Flowmeter\", \"time\", \"Total_Comp_Air\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo ORDER BY \"Flowmeter\" DESC "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 13, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"Bad_Quality_Items\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Live",
   "type": "timeseries",
   "gridPos": { "h": 28, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"Bad_Quality_Items\", \"Good_Quality_Items\", \"Total_Quality_Items\", \"Quality\", \"time\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 13, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"Good_Quality_Items\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"Total_Comp_Air\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 13, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"Total_Quality_Items\" FROM \"TEST\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  }
 ]
}